Repository apache/pulsar-client-cpp, pull requests merged in 2022-12, with the labels that each got.

#133 Fix the broken master by the upgrade of GTest
  .github/workflows/ci-pr-validation.yaml
  tests/KeyValueSchemaTest.cc
Labels: bug, release/3.0

#155 [fix][build] Hide non-exported symbols from the dependencies
  CMakeLists.txt
  README.md
Labels: build

#153 [fix] Fix MessageId serialization when it's a batched message
  .github/workflows/ci-pr-validation.yaml
  lib/BatchMessageAcker.h
  lib/ConsumerImpl.cc
  lib/MessageBatch.cc
  lib/MessageId.cc
  lib/MessageIdBuilder.cc
  tests/MessageIdTest.cc
Labels: bug

#156 [fix] Fix log for connection disconnected expectedly
  include/pulsar/Result.h
  lib/ClientConnection.cc
  lib/ConnectionPool.cc
  lib/Result.cc
  tests/ClientTest.cc
Labels: release/3.0, release/3.1

#158 The C API supports setting the log level.
  examples/CMakeLists.txt
  examples/SampleCustomLoggerCApi.c
  include/pulsar/c/client_configuration.h
  lib/c/c_ClientConfiguration.cc
Labels: enhancement
