Repository apache/pulsar-client-cpp, pull requests merged in 2022-10, with the labels that each got.

#27 [feat] Expose start message id inclusive configuration to C API
  include/pulsar/c/consumer_configuration.h
  lib/c/c_ConsumerConfiguration.cc
  tests/c/c_ConsumerConfigurationTest.cc
Labels: enhancement

#30 Removed extra call of `find_package(OpenSSL)`
  CMakeLists.txt
Labels: build

#33 Enable required check status for PR validation
  .asf.yaml
Labels: build

#34 [docs] Fix compilation guidance on Ubuntu
  README.md
Labels: build

#37 Added option to set the method name for Basic authentication
  include/pulsar/Authentication.h
  lib/Authentication.cc
  lib/auth/AuthBasic.cc
  lib/auth/AuthBasic.h
  tests/AuthBasicTest.cc
Labels: enhancement

#39 Use Alpine 3.12 to build APKs
  pkg/apk/Dockerfile
Labels: build

#40 Improved the CI check completion
  .asf.yaml
  .github/workflows/ci-pr-validation.yaml
Labels: build

#41 Move main to next version
  version.txt
Labels: build

#44 Fix Ubuntu and macOS build guide
  README.md
Labels: documentation

#47 Fixed typos in stage-release.sh
  build-support/stage-release.sh
Labels: build

#36 Use parametrized job to build packages
  .github/workflows/ci-build-binary-artifacts.yaml
  .github/workflows/ci-pr-validation.yaml
Labels: build

#49 Updated Github actions versions to avoid deprecations
  .github/workflows/ci-build-binary-artifacts.yaml
  .github/workflows/ci-pr-validation.yaml
Labels: build

#52 Fixed validation of cluster/namespace names containing legal non-alpha characters
  lib/NamedEntity.cc
  tests/NamespaceNameTest.cc
  tests/TopicNameTest.cc
Labels: bug

#54 [fix] Fix memory leak caused by incorrect close and destruction
  .github/workflows/ci-pr-validation.yaml
  lib/ClientConnection.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/ConnectionPool.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  lib/PartitionedProducerImpl.cc
  lib/PartitionedProducerImpl.h
  lib/PatternMultiTopicsConsumerImpl.cc
  lib/PatternMultiTopicsConsumerImpl.h
  lib/PeriodicTask.cc
  lib/PeriodicTask.h
  lib/ProducerImpl.cc
  lib/ProducerImpl.h
  lib/SynchronizedHashMap.h
  tests/ClientTest.cc
  tests/PulsarFriend.h
  tests/ShutdownTest.cc
  tests/WaitUtils.h
Labels: bug

#57 Fixed the release artifacts package file name
  .github/workflows/ci-build-binary-artifacts.yaml
Labels: build

#45 Stick clang-format version to 11 and add back docker-format.sh
  README.md
  build-support/Dockerfile.format
  build-support/docker-format.sh
  cmake_modules/FindClangTools.cmake
Labels: documentation, build

#22 [feat] Support KeyValue Schema.
  .gitignore
  examples/CMakeLists.txt
  examples/SampleKeyValueSchemaConsumer.cc
  examples/SampleKeyValueSchemaProducer.cc
  include/pulsar/KeyValue.h
  include/pulsar/Message.h
  include/pulsar/MessageBuilder.h
  include/pulsar/Schema.h
  lib/Commands.cc
  lib/ConsumerImpl.cc
  lib/KeyValue.cc
  lib/KeyValueImpl.cc
  lib/KeyValueImpl.h
  lib/Message.cc
  lib/MessageBuilder.cc
  lib/MessageImpl.cc
  lib/MessageImpl.h
  lib/ProducerImpl.cc
  lib/Schema.cc
  tests/KeyValueImplTest.cc
  tests/KeyValueSchemaTest.cc
  tests/MessageTest.cc
  tests/SchemaTest.cc
Labels: enhancement, doc-required

#73 Support linking static dependencies when building with MSVC
  .github/workflows/ci-build-binary-artifacts.yaml
  .github/workflows/ci-pr-validation.yaml
  CMakeLists.txt
  lib/CMakeLists.txt
  win-examples/CMakeLists.txt
  win-examples/example.cc
Labels: build
