Repository apache/pulsar-client-cpp, pull requests merged in 2022-11, with the labels that each got.

#99 [Build] Use Windows server 2019 to release Windows artifacts
  .github/workflows/ci-build-binary-artifacts.yaml
  .github/workflows/ci-pr-validation.yaml
Labels: build, release/3.0

#101 [fix] Fix consumer doesn't clear incomingMessageQueue during seek
  lib/ConsumerImpl.cc
  tests/ConsumerTest.cc
Labels: bug, release/3.0

#98 [fix] Flush no batch message when call producer.flush
  lib/OpSendMsg.h
  lib/ProducerImpl.cc
  tests/ProducerTest.cc
Labels: bug, release/3.0

#103 Fix doxygen generation
  .gitignore
  Doxyfile
  README.md
  docs/MainPage.md
Labels: documentation, release/3.0

#108 Fix MessageId::getDataAsString() crashed with MSVC debug config
  include/pulsar/Message.h
  lib/Message.cc
Labels: bug, release/3.0

#110 [fix] Fix wrong behavior when removing the chunkedMessageCtx
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  tests/MessageChunkingTest.cc
Labels: bug, release/3.0

#105 Add MessageId::batchSize() and the MessageIdBuilder
  include/pulsar/MessageId.h
  include/pulsar/MessageIdBuilder.h
  lib/BatchAcknowledgementTracker.cc
  lib/ClientConnection.cc
  lib/Commands.cc
  lib/Commands.h
  lib/ConsumerImpl.cc
  lib/Message.cc
  lib/MessageAndCallbackBatch.cc
  lib/MessageBatch.cc
  lib/MessageId.cc
  lib/MessageIdBuilder.cc
  lib/MessageIdImpl.h
  lib/MessageIdUtil.h
  lib/NegativeAcksTracker.cc
  lib/ProducerImpl.cc
  lib/UnAckedMessageTrackerEnabled.cc
  tests/BasicEndToEndTest.cc
  tests/BatchMessageTest.cc
  tests/ConsumerTest.cc
  tests/MessageChunkingTest.cc
  tests/MessageIdTest.cc
  tests/PulsarFriend.h
Labels: documentation, enhancement

#118 [feat] Support consumer seek by timestamp and reader seek for C Api
  include/pulsar/c/consumer.h
  include/pulsar/c/reader.h
  lib/c/c_Consumer.cc
  lib/c/c_Reader.cc
  tests/c/c_SeekTest.cc
Labels: enhancement

#117 Fix getLastMessageId method dead recursion.
  lib/Consumer.cc
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerImplBase.h
  lib/GetLastMessageIdResponse.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  tests/ConsumerTest.cc
Labels: bug, release/3.0

#121 Fix segmentation fault during the destruction of ConsumerImpl
  lib/ConsumerImpl.cc
Labels: bug, release/3.0

#128 [fix] Fix acknowledge MessageId list does not work when ackGroupingTimeMs is 0
  lib/AckGroupingTracker.cc
  lib/AckGroupingTrackerDisabled.cc
  lib/AckGroupingTrackerDisabled.h
  lib/AckGroupingTrackerEnabled.cc
  tests/AcknowledgeTest.cc
  tests/BasicEndToEndTest.cc
Labels: bug
