Repository apache/pulsar-client-cpp, pull requests merged in 2023-02, with the labels that each got.

#183 Support the Wireshark plugin for more Wireshark distributions
  .github/workflows/ci-pr-validation.yaml
  CMakeLists.txt
  README.md
  wireshark/CMakeLists.txt
  wireshark/README.md
  wireshark/pulsar-dissector-example.jpg
  wireshark/pulsarDissector.cc
  wireshark/wireshark-plugins.jpg
Labels: documentation, build

#154 [feat] Support partitioned topic reader.
  lib/ClientImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerImplBase.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  lib/ReaderImpl.cc
  lib/ReaderImpl.h
  lib/UnAckedMessageTrackerEnabled.h
  tests/ConsumerTest.cc
  tests/PulsarFriend.h
  tests/ReaderTest.cc
Labels: enhancement

#190 [fix] Use ClientConfiguration::getTlsTrustCertsFilePath for the OAuth2 flow
  lib/ClientConnection.cc
  lib/auth/AuthOauth2.cc
  lib/auth/AuthOauth2.h
  lib/auth/InitialAuthData.h
Labels: bug, cherry-picked/3.0, cherry-picked/3.1

#188 [Fix] NegativeAcksTracker need close when consumer closed.
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/NegativeAcksTracker.cc
  lib/NegativeAcksTracker.h
  tests/ConsumerTest.cc
Labels: bug

#189 [TableView-1] Add table view API
  include/pulsar/Client.h
  include/pulsar/TableView.h
  include/pulsar/TableViewConfiguration.h
Labels: enhancement

#169 [feat] Add producer interceptor
  include/pulsar/Producer.h
  include/pulsar/ProducerConfiguration.h
  include/pulsar/ProducerInterceptor.h
  lib/ClientImpl.cc
  lib/PartitionedProducerImpl.cc
  lib/PartitionedProducerImpl.h
  lib/ProducerConfiguration.cc
  lib/ProducerConfigurationImpl.h
  lib/ProducerImpl.cc
  lib/ProducerImpl.h
  lib/ProducerImplBase.h
  lib/ProducerInterceptors.cc
  lib/ProducerInterceptors.h
  tests/InterceptorsTest.cc
Labels: enhancement

#197 [refactor] Handle responses in methods instead of switch cases
  lib/ClientConnection.cc
  lib/ClientConnection.h
Labels: enhancement

#160 [fix] Redeliver messages that can't be decrypted.
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  tests/ConsumerTest.cc
Labels: bug
