Repository apache/pulsar-client-cpp, pull requests merged in 2023-05, with the labels that each got.

#262 [feat] Support end-to-end encryption in C Reader API
  include/pulsar/c/reader_configuration.h
  lib/c/c_ReaderConfiguration.cc
  tests/c/c_ReaderConfigurationTest.cc
Labels: enhancement

#263 [doc] Fix compile perf on MacOS and Ubuntu.
  README.md
Labels: documentation

#264 [Doc] Add links to client docs and feature matrix in README.md
  README.md
Labels: documentation

#272 Fix batch receive for C client unit test faied.
  tests/c/c_ConsumerTest.cc
Labels: flaky-test

#274 [improve] AuthAthenz supports Copper Argos
  lib/auth/athenz/ZTSClient.cc
  lib/auth/athenz/ZTSClient.h
  tests/ZTSClientTest.cc
Labels: enhancement, doc-required

#276 [feat][consumer] Support parse broker metadata
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/Commands.h
  run-unit-tests.sh
  tests/CMakeLists.txt
  tests/brokermetadata/BrokerMetadataTest.cc
  tests/brokermetadata/docker-compose.yml
  tests/oauth2/Oauth2Test.cc
Labels: enhancement
