Repository apache/pulsar-client-cpp, pull requests merged in 2023-09, with the labels that each got.

#310 Avoid double attempt at reconnecting
  lib/HandlerBase.cc
  lib/HandlerBase.h
Labels: bug

#312 Fix the visibility compilation error for GCC <= 7
  lib/RetryableOperation.h
Labels: bug, build

#313 [fix] Add the curl wrapper to avoid inconsistent curl options
  lib/CurlWrapper.h
  lib/HTTPLookupService.cc
  lib/HTTPLookupService.h
  lib/auth/AuthOauth2.cc
  lib/auth/athenz/ZTSClient.cc
Labels: bug

#316 Fix broken cpp-build-windows workflow
  CMakeLists.txt
Labels: build

#318 Fix broken wireshark build workflow on macOS
  .github/workflows/ci-pr-validation.yaml
Labels: build

#317 Avoid accessing a null ClientConnection instance
  lib/BinaryProtoLookupService.cc
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/ConnectionPool.cc
  lib/ConnectionPool.h
  lib/ConsumerImpl.cc
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/ProducerImpl.cc
  tests/PulsarFriend.h
Labels: bug
