Repository apache/pulsar-client-cpp, pull requests merged in 2023-06, with the labels that each got.

#281 Fix flaky testConsumerEventWithoutPartition cause by the change of Pulsar 3.0
  tests/ConsumerTest.cc
  tests/SynchronizedQueue.h
Labels: flaky-test

#277 [feat][Message] Add getIndex method on Message
  include/pulsar/Message.h
  lib/ClientConnection.cc
  lib/Commands.cc
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/Message.cc
  lib/MessageImpl.cc
  lib/MessageImpl.h
  tests/ConsumerTest.cc
  tests/brokermetadata/BrokerMetadataTest.cc
  tests/brokermetadata/docker-compose.yml
Labels: enhancement

#288 Fix ci failed on macos env.
  .github/workflows/ci-pr-validation.yaml
Labels: build

#291 [feat] Support configure startMessageIdInclusive for the reader
  include/pulsar/ReaderConfiguration.h
  lib/ReaderConfiguration.cc
  lib/ReaderConfigurationImpl.h
  lib/ReaderImpl.cc
  tests/ReaderTest.cc
Labels: enhancement

#293 Fix retriable errors not handled well when creating producer or consumer
  lib/ConsumerImpl.cc
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/ProducerImpl.cc
  tests/ConsumerTest.cc
Labels: bug
