Repository apache/pulsar-client-cpp, pull requests merged in 2023-11, with the labels that each got.

#336 Added support for multiple connections to each broker
  include/pulsar/Client.h
  include/pulsar/ClientConfiguration.h
  lib/Client.cc
  lib/ClientConfiguration.cc
  lib/ClientConfigurationImpl.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/ConnectionPool.cc
  lib/ConnectionPool.h
  perf/PerfConsumer.cc
  perf/PerfProducer.cc
  tests/LookupServiceTest.cc
Labels: enhancement

#337 Fix ProducerBusy or ConsumerBusy error when configuring multiple brokers per connection
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/ConnectionPool.cc
  lib/ConnectionPool.h
  lib/ExecutorService.cc
  lib/ExecutorService.h
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/ProducerImpl.cc
  tests/ProducerTest.cc
  tests/PulsarFriend.h
Labels: bug

#338 Fix close() returns ResultAlreadyClosed after unsubscribe or close
  lib/ConsumerImpl.cc
  tests/BasicEndToEndTest.cc
  tests/ConsumerConfigurationTest.cc
  tests/ConsumerTest.cc
  tests/c/c_BasicEndToEndTest.cc
Labels: bug

#342 Fix lazy partitioned producer might send duplicated messages
  lib/PartitionedProducerImpl.cc
  lib/ProducerImpl.cc
  lib/ProducerImpl.h
  tests/CMakeLists.txt
  tests/chunkdedup/ChunkDedupTest.cc
Labels: bug

#347 Fix crash when removing connection from the pool
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ConnectionPool.cc
  tests/ClientTest.cc
  tests/PulsarFriend.h
Labels: bug

#350 Fix bad_weak_ptr when close a ClientConnection during construction
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ConnectionPool.cc
  tests/AuthPluginTest.cc
Labels: bug

#353 Fix the flush callback might be called repeatedly
  lib/BatchMessageKeyBasedContainer.cc
  lib/ProducerImpl.cc
  tests/ProducerTest.cc
Labels: bug

#354 Fix Protobuf symbols not found in libpulsarwithdeps.a when building on macOS
  .github/workflows/ci-build-binary-artifacts.yaml
  .github/workflows/ci-pr-validation.yaml
  .gitignore
  CMakeLists.txt
  dependencies.yaml
  pkg/mac/build-static-library.sh
Labels: bug, build

#356 Fix HTTP lookup segfault when the redirect host cannot be resolved
  lib/CurlWrapper.h
  lib/HTTPLookupService.cc
Labels: bug
