Repository apache/pulsar-client-cpp, pull requests merged in 2023-03, with the labels that each got.

#206 [improve] Refactor client version format
  lib/Commands.cc
  tests/ClientTest.cc
  tests/HttpHelper.cc
  tests/HttpHelper.h
Labels: enhancement

#203 [fix] Handle exceptions when creating timers when fd limit is reached
  CMakeLists.txt
  lib/ClientConnection.cc
  lib/ClientImpl.cc
  lib/ConnectionPool.cc
  lib/ExecutorService.cc
  lib/ExecutorService.h
  lib/MultiTopicsConsumerImpl.cc
  lib/PartitionedProducerImpl.cc
  lib/PeriodicTask.cc
  lib/PeriodicTask.h
  lib/ProducerImpl.cc
  lib/ProducerImpl.h
  lib/RetryableLookupService.h
  run-unit-tests.sh
  tests/CMakeLists.txt
  tests/PeriodicTaskTest.cc
  tests/unix/ConnectionFailTest.cc
Labels: bug

#196 [TableView-2] Implement all interfaces.
  include/pulsar/Reader.h
  include/pulsar/TableView.h
  lib/Client.cc
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/MultiTopicsConsumerImpl.cc
  lib/SynchronizedHashMap.h
  lib/TableView.cc
  lib/TableViewImpl.cc
  lib/TableViewImpl.h
  tests/PulsarFriend.h
  tests/TableViewTest.cc
Labels: enhancement

#211 Fix Client::close might hang forever for a multi-topics consumer
  lib/MultiTopicsConsumerImpl.cc
  tests/ClientTest.cc
Labels: bug

#216 Fix testPublishEmptyValue flaky test.
  tests/TableViewTest.cc
Labels: flaky-test

#214 Fix flaky testAcknowledgeCumulativeWithPartition
  tests/ConsumerTest.cc
Labels: flaky-test

#217 Fix event loop thread might exit unexpectedly
  .github/workflows/ci-pr-validation.yaml
  lib/ExecutorService.cc
  run-unit-tests.sh
Labels: bug, flaky-test

#218 Use shared_ptr for topic name in message ids
  include/pulsar/Message.h
  include/pulsar/MessageId.h
  lib/BatchMessageContainerBase.h
  lib/Commands.cc
  lib/ConsumerImpl.cc
  lib/ConsumerImplBase.h
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/Message.cc
  lib/MessageBatch.cc
  lib/MessageId.cc
  lib/MessageIdImpl.h
  lib/MessageImpl.cc
  lib/MessageImpl.h
  lib/MultiTopicsConsumerImpl.cc
  lib/ProducerImpl.cc
Labels: bug

#210 [feat] Add consumer interceptor
  include/pulsar/ConsumerConfiguration.h
  include/pulsar/ConsumerInterceptor.h
  include/pulsar/ProducerInterceptor.h
  lib/ClientImpl.cc
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerInterceptors.cc
  lib/ConsumerInterceptors.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  lib/PatternMultiTopicsConsumerImpl.cc
  lib/PatternMultiTopicsConsumerImpl.h
  lib/ReaderImpl.cc
  tests/InterceptorsTest.cc
Labels: enhancement

#223 Make stats timers thread safe to use
  lib/ConsumerImpl.cc
  lib/ProducerImpl.cc
  lib/stats/ConsumerStatsBase.h
  lib/stats/ConsumerStatsImpl.cc
  lib/stats/ConsumerStatsImpl.h
  lib/stats/ProducerStatsBase.h
  lib/stats/ProducerStatsImpl.cc
  lib/stats/ProducerStatsImpl.h
Labels: bug

#222 Fix TableViewTest.testCreateTableView flaky test.
  tests/TableViewTest.cc
Labels: flaky-test

#225 Fix possible crash caused by MessageId::getTopicName
  include/pulsar/MessageId.h
  lib/MessageIdImpl.h
  lib/MultiTopicsConsumerImpl.cc
  tests/AcknowledgeTest.cc
  tests/BasicEndToEndTest.cc
Labels: bug

#220 [feat] Add `onNegativeAcksSend` to the consumer interceptor
  include/pulsar/ConsumerInterceptor.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerInterceptors.cc
  lib/ConsumerInterceptors.h
  lib/NegativeAcksTracker.cc
  tests/InterceptorsTest.cc
Labels: enhancement

#232 Support waiting for the ACK response
  include/pulsar/ConsumerConfiguration.h
  lib/AckGroupingTracker.cc
  lib/AckGroupingTracker.h
  lib/AckGroupingTrackerDisabled.cc
  lib/AckGroupingTrackerDisabled.h
  lib/AckGroupingTrackerEnabled.cc
  lib/AckGroupingTrackerEnabled.h
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/Commands.cc
  lib/Commands.h
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/ConsumerImpl.cc
  tests/AcknowledgeTest.cc
  tests/BasicEndToEndTest.cc
  tests/ConsumerConfigurationTest.cc
Labels: enhancement

#239 [fix][flaky] Remove zero queue case in ConsumerInterceptorTest to reduce flaky
  tests/InterceptorsTest.cc
Labels: flaky-test

#240 Fix ack non-persistent topic will be blocked.
  lib/AckGroupingTracker.h
  tests/ConsumerTest.cc
Labels: bug

#207 [feat] Support pattern subscribe non-persistent topic.
  include/pulsar/ConsumerConfiguration.h
  include/pulsar/RegexSubscriptionMode.h
  lib/BinaryProtoLookupService.cc
  lib/BinaryProtoLookupService.h
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/Commands.cc
  lib/Commands.h
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/HTTPLookupService.cc
  lib/HTTPLookupService.h
  lib/LookupService.h
  lib/MultiTopicsConsumerImpl.h
  lib/PatternMultiTopicsConsumerImpl.cc
  lib/PatternMultiTopicsConsumerImpl.h
  lib/ProtoApiEnums.h
  lib/RetryableLookupService.h
  lib/TopicName.cc
  lib/TopicName.h
  test-conf/standalone-ssl.conf
  tests/ConsumerTest.cc
  tests/LookupServiceTest.cc
  tests/TopicNameTest.cc
Labels: bug

#228 [fix] Consumer batch receive will cause data loss.
  lib/BlockingQueue.h
  lib/ConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.cc
  lib/UnboundedBlockingQueue.h
  tests/BasicEndToEndTest.cc
  tests/BlockingQueueTest.cc
  tests/UnboundedBlockingQueueTest.cc
Labels: bug, release/3.1.3
