Repository apache/pulsar-client-cpp, pull requests merged in 2023-12, with the labels that each got.

#360 Add the Consumer::getConsumerName API
  include/pulsar/Consumer.h
  lib/Consumer.cc
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerImplBase.cc
  lib/ConsumerImplBase.h
  tests/ClientTest.cc
  tests/ConsumerTest.cc
  tests/PulsarAdminHelper.h
Labels: enhancement

#362 Fix accessing destroyed objects in the callback of async_wait
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/MultiTopicsConsumerImpl.cc
  lib/NegativeAcksTracker.cc
  lib/NegativeAcksTracker.h
  lib/PatternMultiTopicsConsumerImpl.cc
  lib/PatternMultiTopicsConsumerImpl.h
  lib/UnAckedMessageTrackerEnabled.cc
  lib/UnAckedMessageTrackerEnabled.h
  lib/UnAckedMessageTrackerInterface.h
  tests/BasicEndToEndTest.cc
  tests/ConsumerTest.cc
Labels: bug

#364 Fix tlsTrustCertsFilePath config is not applied for OAuth2
  lib/ClientConfiguration.cc
  lib/ClientConnection.cc
  lib/auth/AuthOauth2.cc
  run-unit-tests.sh
  tests/oauth2/Oauth2Test.cc
Labels: release/3.4.2

#377 [fix] Fix issue where custom logger setting is ignored
  lib/ClientImpl.cc
  lib/LogUtils.cc
  lib/LogUtils.h
  tests/CustomLoggerTest.cc
Labels: bug
