Repository apache/pulsar-client-cpp, pull requests merged in 2023-01, with the labels that each got.

#149 [feat] Support messages with generic types
  include/pulsar/Consumer.h
  include/pulsar/ConsumerConfiguration.h
  include/pulsar/Message.h
  include/pulsar/MessageBuilder.h
  include/pulsar/TypedMessage.h
  include/pulsar/TypedMessageBuilder.h
  lib/ConsumerImpl.cc
  lib/MessageBuilder.cc
  lib/MultiTopicsConsumerImpl.cc
  tests/TypedMessageTest.cc
Labels: enhancement

#168 Fix segfault caused by socket I/O on a closed io_service
  lib/ClientConnection.cc
  lib/ClientConnection.h
Labels: bug, release/3.0, release/3.1

#171 [fix] Fix missing schema related function definitions
  lib/c/c_Message.cc
Labels: enhancement

#151 [feat] Support batch index acknowledgment
  include/pulsar/ConsumerConfiguration.h
  lib/AckGroupingTracker.cc
  lib/AckGroupingTrackerEnabled.cc
  lib/BatchMessageAcker.h
  lib/BatchedMessageIdImpl.h
  lib/BitSet.h
  lib/Commands.cc
  lib/Commands.h
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/MessageIdImpl.h
  lib/MessageIdUtil.h
  test-conf/standalone-ssl.conf
  tests/AcknowledgeTest.cc
  tests/BitSetTest.cc
  tests/ConsumerConfigurationTest.cc
  tests/ConsumerWrapper.h
Labels: enhancement

#177 Fix broken main branch caused by wrong getBitSet method
  lib/BatchMessageAcker.h
Labels: bug

#176 [feat] Reader support readeNextAsync interface.
  include/pulsar/Reader.h
  include/pulsar/ReaderConfiguration.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/ConsumerImplBase.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  lib/Reader.cc
  lib/ReaderImpl.cc
  lib/ReaderImpl.h
  tests/ReaderTest.cc
Labels: enhancement

#139 [feat] Support Dead Letter Topic.
  include/pulsar/ConsumerConfiguration.h
  include/pulsar/DeadLetterPolicy.h
  include/pulsar/DeadLetterPolicyBuilder.h
  include/pulsar/ProducerConfiguration.h
  lib/Commands.cc
  lib/Commands.h
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  lib/DeadLetterPolicyBuilder.cc
  lib/DeadLetterPolicyImpl.cc
  lib/DeadLetterPolicyImpl.h
  lib/MessageIdImpl.h
  lib/MultiTopicsConsumerImpl.cc
  lib/NegativeAcksTracker.cc
  lib/ProducerConfigurationImpl.h
  lib/ProducerImpl.cc
  tests/ConsumerConfigurationTest.cc
  tests/DeadLetterPolicyTest.cc
  tests/DeadLetterQueueTest.cc
  tests/PulsarFriend.h
Labels: documentation, enhancement

#182 Fix Wireshark build
  wireshark/CMakeLists.txt
  wireshark/README.md
  wireshark/pulsarDissector.cc
Labels: bug
