Repository apache/pulsar-client-cpp, pull requests merged in 2024-03, with the labels that each got.

#408 Fix the incompatibility with Clang and C++20
  .github/workflows/ci-pr-validation.yaml
  lib/NamespaceName.cc
  lib/NamespaceName.h
  lib/TopicName.cc
  lib/TopicName.h
Labels: bug

#411 [improve] add physicalAddress as part of connection pool key
  lib/ClientConnection.cc
  lib/ConnectionPool.cc
  lib/ConnectionPool.h
Labels: enhancement

#413 [fix] Change return code of MultiTopicsConsumerImpl::closeAsync after unsubscribe or close
  lib/MultiTopicsConsumerImpl.cc
  tests/BasicEndToEndTest.cc
Labels: bug

#416 [feat] Add startPaused setting to consumer
  include/pulsar/ConsumerConfiguration.h
  include/pulsar/c/consumer_configuration.h
  lib/ConsumerConfiguration.cc
  lib/ConsumerConfigurationImpl.h
  lib/ConsumerImpl.cc
  lib/c/c_ConsumerConfiguration.cc
  tests/BasicEndToEndTest.cc
Labels: enhancement

#414 Fix broken wireshark build workflow on macOS
  .github/workflows/ci-pr-validation.yaml
Labels: build, tests

#422 Fix wrong results of hasMessageAvailable and readNext after seeking by timestamp
  lib/ConsumerImpl.cc
  lib/ConsumerImpl.h
  tests/ReaderTest.cc
Labels: bug, release/3.5.1
