Repository apache/pulsar-client-cpp, pull requests merged in 2024-02, with the labels that each got.

#388 Fix multi-topics consumer could receive old messages after seek
  lib/ConsumerImpl.h
  lib/MultiResultCallback.h
  lib/MultiTopicsConsumerImpl.cc
  lib/MultiTopicsConsumerImpl.h
  tests/MultiTopicsConsumerTest.cc
  tests/ThreadSafeMessages.h
Labels: bug

#400 Fix broken main branch after Pulsar image was upgraded to 3.2.0
  lib/ClientConnection.cc
  tests/extensibleLM/ExtensibleLoadManagerTest.cc
Labels: tests

#399 Fix segmenatation fault if connection is closed during handshake
  lib/ClientConnection.cc
Labels: bug

#10 Add codeql code scanning configuration
  .github/workflows/codeql-analysis.yml
Labels: build, security

#396 Fix creating producer or consumer is not retried for connection failure
  lib/ClientConnection.cc
  lib/ClientConnectionAdaptor.h
  lib/ClientImpl.cc
  lib/ClientImpl.h
  lib/ConsumerImpl.cc
  lib/Future.h
  lib/HandlerBase.cc
  lib/HandlerBase.h
  lib/ProducerImpl.cc
  lib/ResultUtils.h
  tests/ClientTest.cc
  tests/MockClientImpl.h
Labels: bug

#403 Disable batch send for dlq producer.
  lib/ConsumerImpl.cc
  tests/DeadLetterQueueTest.cc
Labels: enhancement

#406 Fix blue-green migration might be stuck due to an existing reconnection
  lib/ClientConnection.cc
  lib/ClientConnection.h
  lib/ConsumerImpl.cc
  lib/HandlerBase.h
  lib/ProducerImpl.cc
  lib/stats/ConsumerStatsBase.h
  lib/stats/ConsumerStatsImpl.h
  tests/PulsarFriend.h
  tests/extensibleLM/ExtensibleLoadManagerTest.cc
Labels: bug

#404 Update dependencies to latest versions
  dependencies.yaml
  pkg/apk/Dockerfile
  pkg/deb/Dockerfile
  pkg/mac/build-static-library.sh
  pkg/rpm/Dockerfile
Labels: build
