Repository apache/pulsar-client-cpp, pull requests merged in 2024-01, with the labels that each got.

#380 Remove the Boost.Random dependency
  lib/Backoff.cc
  lib/Backoff.h
  lib/RoundRobinMessageRouter.cc
  vcpkg.json
Labels: enhancement

#384 Fix Boost source code download failure
  dependencies.yaml
  pkg/apk/Dockerfile
  pkg/deb/Dockerfile
  pkg/mac/build-static-library.sh
  pkg/rpm/Dockerfile
Labels: build

#386 Fix `StartMessageIdInclusive` not work when reader reads from latest msg id
  lib/ConsumerImpl.cc
  tests/ReaderTest.cc
Labels: bug

#387 Fix wrong TimeUtils::currentTimeMillis() implementation
  lib/TimeUtils.h
  tests/BackoffTest.cc
Labels: bug
